--------------------------------------------------------
-- Archivo creado  - lunes-julio-18-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CATEGORIA
--------------------------------------------------------

  CREATE TABLE "TRACKMASTER"."CATEGORIA" 
   (	"IDCATEGORIA" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DETALLEPEDIDO
--------------------------------------------------------

  CREATE TABLE "TRACKMASTER"."DETALLEPEDIDO" 
   (	"IDPEDIDO" NUMBER(*,0), 
	"IDPRODUCTO" NUMBER(*,0), 
	"CANTIDAD" NUMBER(*,0), 
	"SUBTOTAL" FLOAT(126)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOCALIZACION
--------------------------------------------------------

  CREATE TABLE "TRACKMASTER"."LOCALIZACION" 
   (	"IDPEDIDO" NUMBER(*,0), 
	"IDLOCALIZACION" NUMBER(*,0), 
	"IDUSUARIO" VARCHAR2(30 BYTE), 
	"LONGITUD" VARCHAR2(17 BYTE), 
	"LATITUD" VARCHAR2(17 BYTE), 
	"FECHA" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PEDIDO
--------------------------------------------------------

  CREATE TABLE "TRACKMASTER"."PEDIDO" 
   (	"IDPEDIDO" NUMBER(*,0), 
	"FECHAPEDIDO" DATE, 
	"TOTAL" FLOAT(126), 
	"ESTADO" VARCHAR2(30 BYTE), 
	"IDUSUARIO" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTO
--------------------------------------------------------

  CREATE TABLE "TRACKMASTER"."PRODUCTO" 
   (	"IDPRODUCTO" NUMBER(*,0), 
	"MARCA" VARCHAR2(30 BYTE), 
	"MODELO" VARCHAR2(30 BYTE), 
	"DESCRIPCION" VARCHAR2(30 BYTE), 
	"PRECIOUNITARIO" FLOAT(5), 
	"STOCK" NUMBER(*,0), 
	"IDCATEGORIA" NUMBER(*,0), 
	"URLIMAGEN" VARCHAR2(300 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "TRACKMASTER"."USUARIO" 
   (	"IDUSUARIO" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"ESTADO" VARCHAR2(30 BYTE), 
	"DIRECCIONENVIO" VARCHAR2(30 BYTE), 
	"ROL" VARCHAR2(30 BYTE), 
	"APELLIDO" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TRACKMASTER.CATEGORIA
SET DEFINE OFF;
Insert into TRACKMASTER.CATEGORIA (IDCATEGORIA,DESCRIPCION) values (1,'Aires acondicionados');
Insert into TRACKMASTER.CATEGORIA (IDCATEGORIA,DESCRIPCION) values (2,'LED');
Insert into TRACKMASTER.CATEGORIA (IDCATEGORIA,DESCRIPCION) values (3,'Celulares');
Insert into TRACKMASTER.CATEGORIA (IDCATEGORIA,DESCRIPCION) values (4,'PC');
Insert into TRACKMASTER.CATEGORIA (IDCATEGORIA,DESCRIPCION) values (5,'Accesorios USB');
Insert into TRACKMASTER.CATEGORIA (IDCATEGORIA,DESCRIPCION) values (6,'Accesorios para celular');
Insert into TRACKMASTER.CATEGORIA (IDCATEGORIA,DESCRIPCION) values (7,'Accesorios para auto');
Insert into TRACKMASTER.CATEGORIA (IDCATEGORIA,DESCRIPCION) values (8,'Casa y oficina');
Insert into TRACKMASTER.CATEGORIA (IDCATEGORIA,DESCRIPCION) values (9,'Interiores');
Insert into TRACKMASTER.CATEGORIA (IDCATEGORIA,DESCRIPCION) values (10,'Exteriores');
Insert into TRACKMASTER.CATEGORIA (IDCATEGORIA,DESCRIPCION) values (11,'Iluminacion');
Insert into TRACKMASTER.CATEGORIA (IDCATEGORIA,DESCRIPCION) values (12,'Calefaccion');
Insert into TRACKMASTER.CATEGORIA (IDCATEGORIA,DESCRIPCION) values (13,'Cocinas');
Insert into TRACKMASTER.CATEGORIA (IDCATEGORIA,DESCRIPCION) values (14,'Lavarropas');
Insert into TRACKMASTER.CATEGORIA (IDCATEGORIA,DESCRIPCION) values (15,'Deportes');
Insert into TRACKMASTER.CATEGORIA (IDCATEGORIA,DESCRIPCION) values (16,'Fragancias');
Insert into TRACKMASTER.CATEGORIA (IDCATEGORIA,DESCRIPCION) values (17,'Salud y belleza');
Insert into TRACKMASTER.CATEGORIA (IDCATEGORIA,DESCRIPCION) values (18,'Camaras');
Insert into TRACKMASTER.CATEGORIA (IDCATEGORIA,DESCRIPCION) values (19,'Anteojos');
Insert into TRACKMASTER.CATEGORIA (IDCATEGORIA,DESCRIPCION) values (20,'Relojes');
Insert into TRACKMASTER.CATEGORIA (IDCATEGORIA,DESCRIPCION) values (21,'Tablets');
Insert into TRACKMASTER.CATEGORIA (IDCATEGORIA,DESCRIPCION) values (22,'Videojuegos');
Insert into TRACKMASTER.CATEGORIA (IDCATEGORIA,DESCRIPCION) values (23,'RadioControl');
Insert into TRACKMASTER.CATEGORIA (IDCATEGORIA,DESCRIPCION) values (24,'Linternas');
Insert into TRACKMASTER.CATEGORIA (IDCATEGORIA,DESCRIPCION) values (25,'Ropa');
REM INSERTING into TRACKMASTER.DETALLEPEDIDO
SET DEFINE OFF;
Insert into TRACKMASTER.DETALLEPEDIDO (IDPEDIDO,IDPRODUCTO,CANTIDAD,SUBTOTAL) values (3,1,1,4000);
Insert into TRACKMASTER.DETALLEPEDIDO (IDPEDIDO,IDPRODUCTO,CANTIDAD,SUBTOTAL) values (5,1,1,4000);
Insert into TRACKMASTER.DETALLEPEDIDO (IDPEDIDO,IDPRODUCTO,CANTIDAD,SUBTOTAL) values (5,2,1,6000);
Insert into TRACKMASTER.DETALLEPEDIDO (IDPEDIDO,IDPRODUCTO,CANTIDAD,SUBTOTAL) values (4,2,1,6000);
Insert into TRACKMASTER.DETALLEPEDIDO (IDPEDIDO,IDPRODUCTO,CANTIDAD,SUBTOTAL) values (6,2,1,6000);
Insert into TRACKMASTER.DETALLEPEDIDO (IDPEDIDO,IDPRODUCTO,CANTIDAD,SUBTOTAL) values (6,3,1,3600);
Insert into TRACKMASTER.DETALLEPEDIDO (IDPEDIDO,IDPRODUCTO,CANTIDAD,SUBTOTAL) values (2,1,1,4000);
REM INSERTING into TRACKMASTER.LOCALIZACION
SET DEFINE OFF;
REM INSERTING into TRACKMASTER.PEDIDO
SET DEFINE OFF;
Insert into TRACKMASTER.PEDIDO (IDPEDIDO,FECHAPEDIDO,TOTAL,ESTADO,IDUSUARIO) values (3,to_date('10-JUL-16','DD-MON-RR'),4000,'EN_TRANSITO','marco1');
Insert into TRACKMASTER.PEDIDO (IDPEDIDO,FECHAPEDIDO,TOTAL,ESTADO,IDUSUARIO) values (1,to_date('03-JUL-16','DD-MON-RR'),1000,'EN TRANSITO','marco1');
Insert into TRACKMASTER.PEDIDO (IDPEDIDO,FECHAPEDIDO,TOTAL,ESTADO,IDUSUARIO) values (5,to_date('10-JUL-16','DD-MON-RR'),10000,'EN_TRANSITO','marco1');
Insert into TRACKMASTER.PEDIDO (IDPEDIDO,FECHAPEDIDO,TOTAL,ESTADO,IDUSUARIO) values (6,to_date('10-JUL-16','DD-MON-RR'),9600,'EN_TRANSITO','marco1');
Insert into TRACKMASTER.PEDIDO (IDPEDIDO,FECHAPEDIDO,TOTAL,ESTADO,IDUSUARIO) values (2,to_date('10-JUL-16','DD-MON-RR'),4000,'EN_TRANSITO','marco1');
Insert into TRACKMASTER.PEDIDO (IDPEDIDO,FECHAPEDIDO,TOTAL,ESTADO,IDUSUARIO) values (4,to_date('10-JUL-16','DD-MON-RR'),6000,'EN_TRANSITO','marco1');
REM INSERTING into TRACKMASTER.PRODUCTO
SET DEFINE OFF;
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (1,'samsung','galaxy j1','smartphone ',4000,100,1,'http://fravega.vteximg.com.br/arquivos/ids/281163-1000-1000/780712_1.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (2,'samsung','grand Prime','smartphone ',6000,50,1,'http://fravega.vteximg.com.br/arquivos/ids/275446-1000-1000/CELULAR-LIBRE-SAMSUNG-GRAND-PRIME-WHITE-4G.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (3,'Admiral','a506','smartphone ',3600,50,1,'http://fravega.vteximg.com.br/arquivos/ids/274191-1000-1000/780486_1.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (4,'Firstar','w402','celular',1900,100,1,'http://fravega.vteximg.com.br/arquivos/ids/278991-1000-1000/780577_7.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (5,'samsung','galaxy a3','smartphone ',7000,150,1,'http://fravega.vteximg.com.br/arquivos/ids/273474-1000-1000/780492_1.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (6,'samsung','galaxy a5','smartphone ',9000,200,1,'http://fravega.vteximg.com.br/arquivos/ids/273645-1000-1000/CELULAR-LIBRE-SAMSUNG-GALAXY-A5-WHITE.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (7,'Motorola','moto e4g','smartphone ',5000,300,1,'http://fravega.vteximg.com.br/arquivos/ids/269122-1000-1000/CELULAR-LIBRE-MOTOROLA-MOTO-E-2DA-GENERACION.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (8,'Hyundai','ultra latitud','smartphone ',5000,270,1,'http://fravega.vteximg.com.br/arquivos/ids/276396-1000-1000/CELULAR-LIBRE-HYUNDAI-ULTRA-LATITUD.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (9,'LG','g3 titanium','smartphone ',10000,50,1,'http://fravega.vteximg.com.br/arquivos/ids/262465-1000-1000/780244_1.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (10,'Microsoft','Lumia 640 XL','smartphone ',5000,25,1,'http://fravega.vteximg.com.br/arquivos/ids/279977-1000-1000/780905_1.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (11,'Shinecon','Vr shinecon','gafas realidad virtual ',700,150,6,'http://miniimg3.rightinthebox.com/images/384x384/201601/ufwysp1453195525121.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (12,'Xbox','bateria xbox','bareria recargable',50,60,6,'http://miniimg1.rightinthebox.com/images/384x384/201404/bgwwyx1397644414930.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (14,'Xbox ONE','carcaza xbox ONE','funda dorada para joystick ',150,25,22,'http://miniimg1.rightinthebox.com/images/384x384/201406/rxazxo1401766340339.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (15,'Sony','dualshock3','joystick playstation3',1000,80,22,'http://fravega.vteximg.com.br/arquivos/ids/276099-1000-1000/JOYSTICK-SONY-DUALSHOCK-3.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (16,'Xbox 360','xbox 500GB Call of dutty','Consola para videojuegos',8500,35,22,'http://fravega.vteximg.com.br/arquivos/ids/279711-1000-1000/341508_1.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (17,'Sony','playstation 4 500GB','Consola para videojuegos',13000,20,22,'http://fravega.vteximg.com.br/arquivos/ids/270934-1000-1000/341374_1.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (20,'Xbox','halo + kinect','Consola para videojuegos',15000,8,22,'http://fravega.vteximg.com.br/arquivos/ids/275691-1000-1000/341540_1.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (21,'Pioneer','mhv','stereo para auto',1800,230,7,'http://fravega.vteximg.com.br/arquivos/ids/269430-1000-1000/STEREO-PIONEER-MVH-075UBP.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (22,'Garmin','nuvi 67','GPS para auto',4600,190,7,'http://fravega.vteximg.com.br/arquivos/ids/275390-1000-1000/460346_1.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (23,'Targa Tag','tag 9640','parlantes para auto',900,63,7,'http://fravega.vteximg.com.br/arquivos/ids/276511-1000-1000/460168_1.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (24,'Philco','cspr1','parlantes para auto',600,90,7,'http://fravega.vteximg.com.br/arquivos/ids/269641-1000-1000/PARLANTE-PHILCO-CSPR1630.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (25,'X-view','venture 7 tv','GPS para auto',120,2800,7,'http://fravega.vteximg.com.br/arquivos/ids/256158-1000-1000/GPS-X-VIEW-VENTURE-7---T.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (26,'R-Sim','nano micro sim','adaptador para SIM',30,300,6,'http://mla-s2-p.mlstatic.com/adaptador-nano-micro-sim-celular-x-3-clip-10944-MLA20036350898_012014-O.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (27,'Damse','MLA','soporte para cargar celular',50,500,6,'http://mla-s2-p.mlstatic.com/apoya-celulares-cargar-bateria-accesorios-x-500-un-mayorista-781311-MLA20523878124_122015-O.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (29,'Noaf','Noaf running','Bolsillo grande para celular',200,80,6,'http://mla-s1-p.mlstatic.com/bolsillo-grande-xl-porta-smartphone-noaf-running-accesorio-262111-MLA20492134438_112015-O.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (30,'Motorola','atrix','docking para celular Motorola',560,10,6,'http://mla-s1-p.mlstatic.com/dock-motorola-atrix-accesorios-originales-nuevo-12247-MLA20057474200_032014-O.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (31,'Phillips','orbits','l�ara 1 LED',1200,23,2,'http://fravega.vteximg.com.br/arquivos/ids/264442-1000-1000/670161_1.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (32,'Phillips','mendel','iluminaria de pared',1500,5,2,'http://fravega.vteximg.com.br/arquivos/ids/264294-1000-1000/670101_3.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (33,'Phillips','ledino','iluminaria colgante',8200,2,2,'http://fravega.vteximg.com.br/arquivos/ids/264418-1000-1000/670011_1.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (34,'Phillips','vision 2LED','iluminario con 2 LED',3500,5,2,'http://fravega.vteximg.com.br/arquivos/ids/264456-1000-1000/670131_1.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (36,'Casio','G-shock','reloj hombre',3900,5,16,'http://mla-s1-p.mlstatic.com/653211-MLA20503945324_112015-R.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (38,'Skmei','skm 1040','reloj outdoor',700,10,18,'http://mla-s2-p.mlstatic.com/skmei-reloj-outdoor-hora-dual-alarma-cronografo-luz-24-hs-102211-MLA20485535575_112015-O.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (39,'Adidas','adh2983','reloj hombre',2500,9,19,'http://mla-s1-p.mlstatic.com/reloj-adidas-adh2983-mens-brisbane-black-cronografo-100m-wr-497311-MLA20546903962_012016-O.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (40,'Festina','f16844','reloj hombre',3500,2,20,'http://mla-s2-p.mlstatic.com/reloj-festina-f16844-crono-50m-taquimetro-envio-823011-MLA20458269154_102015-O.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (41,'Samsung','galaxy tab','tablet 9,6 pulgadas',5000,89,21,'http://fravega.vteximg.com.br/arquivos/ids/278245-1000-1000/700270_1.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (43,'Admiral','a71l','tablet 7 pulgadas',1300,60,21,'http://fravega.vteximg.com.br/arquivos/ids/277765-1000-1000/_MG_9670-copy.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (44,'BGH','y210','tablet 7 pulgadas con android',1600,50,21,'http://fravega.vteximg.com.br/arquivos/ids/281229-1000-1000/700368_1.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (45,'EXO','wave l101 il','tablet Android 4.4.4',4500,35,21,'http://fravega.vteximg.com.br/arquivos/ids/276196-1000-1000/TABLET-EXO-WAVE-I101-IL.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (46,'ViewSonic','ir7q 7','tablet 7 pulgadas',2300,20,21,'http://fravega.vteximg.com.br/arquivos/ids/277452-1000-1000/700339_1.jpg');
Insert into TRACKMASTER.PRODUCTO (IDPRODUCTO,MARCA,MODELO,DESCRIPCION,PRECIOUNITARIO,STOCK,IDCATEGORIA,URLIMAGEN) values (50,'Interelec','inter-9002','linterna con 19 LED',850,50,24,'http://mla-s2-p.mlstatic.com/linterna-baliza-recargable-de-19-leds-220v-con-bateria-16588-MLA20123158844_072014-O.jpg');
REM INSERTING into TRACKMASTER.USUARIO
SET DEFINE OFF;
Insert into TRACKMASTER.USUARIO (IDUSUARIO,PASSWORD,NOMBRE,EMAIL,ESTADO,DIRECCIONENVIO,ROL,APELLIDO) values ('idUsuario','password','nombre','email','estado ','direccionEnvio','Rol','apellido');
Insert into TRACKMASTER.USUARIO (IDUSUARIO,PASSWORD,NOMBRE,EMAIL,ESTADO,DIRECCIONENVIO,ROL,APELLIDO) values ('marco1','abc','marco','marco_morani@gmail.com','activo','reina victoria 56','cliente','morani');
Insert into TRACKMASTER.USUARIO (IDUSUARIO,PASSWORD,NOMBRE,EMAIL,ESTADO,DIRECCIONENVIO,ROL,APELLIDO) values ('andres1','abc','andres','andres.salazar@gmail.com','activo','lucero 2','cliente','salazar');
Insert into TRACKMASTER.USUARIO (IDUSUARIO,PASSWORD,NOMBRE,EMAIL,ESTADO,DIRECCIONENVIO,ROL,APELLIDO) values ('milena1','abc','milena','milsimoni@gmail.com','activo','pasaje tona 7','cliente','simoni');
Insert into TRACKMASTER.USUARIO (IDUSUARIO,PASSWORD,NOMBRE,EMAIL,ESTADO,DIRECCIONENVIO,ROL,APELLIDO) values ('dan','abc','dan','danangel@gmail.com','activo','libreros 25','cliente','angel');
Insert into TRACKMASTER.USUARIO (IDUSUARIO,PASSWORD,NOMBRE,EMAIL,ESTADO,DIRECCIONENVIO,ROL,APELLIDO) values ('francisco','abc','francisco','fluna@gmail.com','activo','comunidad 25','cliente','luna');
Insert into TRACKMASTER.USUARIO (IDUSUARIO,PASSWORD,NOMBRE,EMAIL,ESTADO,DIRECCIONENVIO,ROL,APELLIDO) values ('soledad','abc','soledad','solespejo2@outlook.com','activo','gran via 23','cliente','espejo');
Insert into TRACKMASTER.USUARIO (IDUSUARIO,PASSWORD,NOMBRE,EMAIL,ESTADO,DIRECCIONENVIO,ROL,APELLIDO) values ('fernando','abc','fernando','fernanlobo@outlook.com','activo','calle 2 esquina calle 5','cliente','wolf');
Insert into TRACKMASTER.USUARIO (IDUSUARIO,PASSWORD,NOMBRE,EMAIL,ESTADO,DIRECCIONENVIO,ROL,APELLIDO) values ('elizabeth','abc','elizabeth','eliflores98@outloo.com','activo','av. Del puerto 33','cliente','flores');
Insert into TRACKMASTER.USUARIO (IDUSUARIO,PASSWORD,NOMBRE,EMAIL,ESTADO,DIRECCIONENVIO,ROL,APELLIDO) values ('geronimo','abc','geronimo','geronimometal@outlook.com','activo','av arroyos 12','cliente','aguirre');
Insert into TRACKMASTER.USUARIO (IDUSUARIO,PASSWORD,NOMBRE,EMAIL,ESTADO,DIRECCIONENVIO,ROL,APELLIDO) values ('maria','abc','maria','mariajusto@yahoo.com','activo','henderson 67','cliente','justo');
Insert into TRACKMASTER.USUARIO (IDUSUARIO,PASSWORD,NOMBRE,EMAIL,ESTADO,DIRECCIONENVIO,ROL,APELLIDO) values ('victoria','abc','victoria','vickygutierrez@yahoo.com','activo','Juan B. Justo 1000','cliente','gutierrez');
Insert into TRACKMASTER.USUARIO (IDUSUARIO,PASSWORD,NOMBRE,EMAIL,ESTADO,DIRECCIONENVIO,ROL,APELLIDO) values ('daniel','abc','daniel','danielemos@hotmail.com','activo','la gloria 34','cliente','lemos');
Insert into TRACKMASTER.USUARIO (IDUSUARIO,PASSWORD,NOMBRE,EMAIL,ESTADO,DIRECCIONENVIO,ROL,APELLIDO) values ('felipe','abc','felipe','zaragoza.feli@hotmail.com','activo','paredes 51','cliente','zaragoza');
Insert into TRACKMASTER.USUARIO (IDUSUARIO,PASSWORD,NOMBRE,EMAIL,ESTADO,DIRECCIONENVIO,ROL,APELLIDO) values ('arturo','abc','arturo','artiguillen@hotmail.com','activo','elcano 20','cliente','guillen');
Insert into TRACKMASTER.USUARIO (IDUSUARIO,PASSWORD,NOMBRE,EMAIL,ESTADO,DIRECCIONENVIO,ROL,APELLIDO) values ('jos�bc','jos�blanco@hotmail.com','activo','av. Baleares 45','cliente','blanco',null,null);
Insert into TRACKMASTER.USUARIO (IDUSUARIO,PASSWORD,NOMBRE,EMAIL,ESTADO,DIRECCIONENVIO,ROL,APELLIDO) values ('cecilia','abc','cecilia','cecigonzalez@hotmail.com','activo','finisterre 30','cliente','gonzalez');
Insert into TRACKMASTER.USUARIO (IDUSUARIO,PASSWORD,NOMBRE,EMAIL,ESTADO,DIRECCIONENVIO,ROL,APELLIDO) values ('cuyen','abc','cuyen','lacuyenga@hotmail.com','activo','la serena 3431','administrativo','garcia');
Insert into TRACKMASTER.USUARIO (IDUSUARIO,PASSWORD,NOMBRE,EMAIL,ESTADO,DIRECCIONENVIO,ROL,APELLIDO) values ('daiana','abc','daiana','daisevilla@hotmail.com','activo','ciudad de ronda 10','administrativo','sevilla');
--------------------------------------------------------
--  DDL for Index pedido PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRACKMASTER"."pedido PK" ON "TRACKMASTER"."PEDIDO" ("IDPEDIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DetallePedido PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRACKMASTER"."DetallePedido PK" ON "TRACKMASTER"."DETALLEPEDIDO" ("IDPRODUCTO", "IDPEDIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index Categoria PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRACKMASTER"."Categoria PK" ON "TRACKMASTER"."CATEGORIA" ("IDCATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index Usuario PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRACKMASTER"."Usuario PK" ON "TRACKMASTER"."USUARIO" ("IDUSUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index localizacion PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRACKMASTER"."localizacion PK" ON "TRACKMASTER"."LOCALIZACION" ("IDPEDIDO", "IDLOCALIZACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index Producto PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRACKMASTER"."Producto PK" ON "TRACKMASTER"."PRODUCTO" ("IDPRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PEDIDO
--------------------------------------------------------

  ALTER TABLE "TRACKMASTER"."PEDIDO" MODIFY ("IDPEDIDO" NOT NULL ENABLE);
 
  ALTER TABLE "TRACKMASTER"."PEDIDO" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
 
  ALTER TABLE "TRACKMASTER"."PEDIDO" ADD CONSTRAINT "pedido PK" PRIMARY KEY ("IDPEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "TRACKMASTER"."USUARIO" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
 
  ALTER TABLE "TRACKMASTER"."USUARIO" ADD CONSTRAINT "Usuario PK" PRIMARY KEY ("IDUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DETALLEPEDIDO
--------------------------------------------------------

  ALTER TABLE "TRACKMASTER"."DETALLEPEDIDO" ADD CONSTRAINT "DetallePedido PK" PRIMARY KEY ("IDPRODUCTO", "IDPEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TRACKMASTER"."DETALLEPEDIDO" MODIFY ("IDPEDIDO" NOT NULL ENABLE);
 
  ALTER TABLE "TRACKMASTER"."DETALLEPEDIDO" MODIFY ("IDPRODUCTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "TRACKMASTER"."PRODUCTO" ADD CONSTRAINT "Producto PK" PRIMARY KEY ("IDPRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TRACKMASTER"."PRODUCTO" MODIFY ("IDPRODUCTO" NOT NULL ENABLE);
 
  ALTER TABLE "TRACKMASTER"."PRODUCTO" MODIFY ("IDCATEGORIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORIA
--------------------------------------------------------

  ALTER TABLE "TRACKMASTER"."CATEGORIA" ADD CONSTRAINT "Categoria PK" PRIMARY KEY ("IDCATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TRACKMASTER"."CATEGORIA" MODIFY ("IDCATEGORIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOCALIZACION
--------------------------------------------------------

  ALTER TABLE "TRACKMASTER"."LOCALIZACION" MODIFY ("IDPEDIDO" NOT NULL ENABLE);
 
  ALTER TABLE "TRACKMASTER"."LOCALIZACION" MODIFY ("IDLOCALIZACION" NOT NULL ENABLE);
 
  ALTER TABLE "TRACKMASTER"."LOCALIZACION" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
 
  ALTER TABLE "TRACKMASTER"."LOCALIZACION" ADD CONSTRAINT "localizacion PK" PRIMARY KEY ("IDPEDIDO", "IDLOCALIZACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table DETALLEPEDIDO
--------------------------------------------------------

  ALTER TABLE "TRACKMASTER"."DETALLEPEDIDO" ADD CONSTRAINT "FK_PEDIDO_DETALLEPPPEDIDO" FOREIGN KEY ("IDPEDIDO")
	  REFERENCES "TRACKMASTER"."PEDIDO" ("IDPEDIDO") ENABLE;
 
  ALTER TABLE "TRACKMASTER"."DETALLEPEDIDO" ADD CONSTRAINT "FK_PRODUCTO_DETALLEPEDIDO" FOREIGN KEY ("IDPRODUCTO")
	  REFERENCES "TRACKMASTER"."PRODUCTO" ("IDPRODUCTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOCALIZACION
--------------------------------------------------------

  ALTER TABLE "TRACKMASTER"."LOCALIZACION" ADD CONSTRAINT "FK_LOCALIZACION_PEDIDO" FOREIGN KEY ("IDPEDIDO")
	  REFERENCES "TRACKMASTER"."PEDIDO" ("IDPEDIDO") ENABLE;
 
  ALTER TABLE "TRACKMASTER"."LOCALIZACION" ADD CONSTRAINT "FK_LOCALIZACION_USUARIO" FOREIGN KEY ("IDUSUARIO")
	  REFERENCES "TRACKMASTER"."USUARIO" ("IDUSUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PEDIDO
--------------------------------------------------------

  ALTER TABLE "TRACKMASTER"."PEDIDO" ADD CONSTRAINT "FK_PEDIDO_USUARIO" FOREIGN KEY ("IDUSUARIO")
	  REFERENCES "TRACKMASTER"."USUARIO" ("IDUSUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "TRACKMASTER"."PRODUCTO" ADD CONSTRAINT "FK_CATEGORIAPRODUCTO" FOREIGN KEY ("IDCATEGORIA")
	  REFERENCES "TRACKMASTER"."CATEGORIA" ("IDCATEGORIA") ENABLE;

--------------------------------------------------------
--  DDL for Procedure CHECK_USER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "TRACKMASTER"."CHECK_USER" (c OUT SYS_REFCURSOR, nom_idUser IN varchar)
AS 
BEGIN
  OPEN c FOR SELECT *
  FROM usuario
  WHERE idusuario=nom_idUser;
END CHECK_USER;

/
